create 长期汉化跟进pr
LWHK/Create pull request #1
Opened 2020-08-10 10:38 UTC by TUsama

用于挂载我本地的仓库更改，有问题可以及时review。

2020-08-10 11:22 UTC, MacrousHyucen requested changes
两处影响阅读的细微错误，辛苦更改。

2020-08-10 11:22 UTC, MacrousHyucen commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"block.create.blaze_heater.tooltip.behaviour1": "将一只烈焰人_捕捉_近该物品中。",
近——进

2020-08-10 11:22 UTC, MacrousHyucen commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.blockzapper.component.retriever": "回捡",
？

2020-08-10 11:35 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.blockzapper.component.retriever": "回捡",
https://github.com/Imbarainbow/Create/wiki/%E6%89%8B%E6%8C%81%E6%96%B9%E5%9D%97%E6%94%BE%E7%BD%AE%E5%99%A8#%E6%96%B9%E5%9D%97%E9%87%87%E9%9B%86-%E5%9B%9E%E6%8D%A1

这个我是存疑的，因为原文是Retriever，取的是“捡回”的意思，这里加了个-r是想要强调“角色”之意，整意为“将物品捡回的部件”（这么一说，上面的全部都要改了）。译为“寻回”我个人觉得略显不妥，此处无物可寻，因为替换之后的方块并没有被隐藏，还是清晰地“显露”的，并不需要放置器“寻回”，准确来说，它的目的是“重定位”（relocated）。基于上述考虑，我翻译为了“回捡”。考虑到方块放置器的升级逻辑为部件-部件提升性能，所以这里应该翻译为“....器”，原来我没有考虑到，待会会更改过来

2020-08-11 05:28 UTC, MacrousHyucen commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"block.create.blue_seat": "蓝色座椅",
1

2020-08-11 05:28 UTC, MacrousHyucen commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.black_seat": "黑色座椅",
1

2020-08-11 10:32 UTC, TUsama commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"block.create.andesite_chute_funnel": "安山岩溜槽漏斗",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

此处与香蕉的不一致

2020-08-11 10:32 UTC, TUsama commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"block.create.blaze_burner": "烈焰人燃烧室",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

同理

2020-08-11 10:32 UTC, TUsama commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"block.create.brass_chute_funnel": "黄铜溜槽漏斗",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

同理

2020-08-11 10:32 UTC, TUsama commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"block.create.mechanical_arm": "动力臂",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

“动力机械臂”和“动力臂”二择一

2020-08-11 10:33 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.gui.blockzapper.searchDiagonal": "对角线延伸",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

方块放置器部分的改动较大，可以仔细看看

2020-08-11 10:33 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.blockzapper.component.body": "放置器机体",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

尤其是这部分

2020-08-11 14:37 UTC, FishInMars approved these changes

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"advancement.create.its_alive.desc": "首次激活齿轮结构的旋转.",
. -> 。

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.recipe.pressing": "金属压板",
金属辊压？

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
>  	"advancement.create.overstressed.desc": "首次使能量网络超载.",
. -> 。

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.gui.stockpile_switch.stopBelow": "停止红石信号当容量小于",
672 & 674 语序是否有问题

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.cuckoo_clock.tooltip.behaviour1": "显示 _当前时间_ 并且一天会咕咕_两次_.中午咕咕一次， 黄昏可以睡觉的时候咕咕一次 。",
句号前空格

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.mechanical_press.tooltip.behaviour3": "一旦所有必要的原料都出现，就会开始对这些_物品_进行_压缩_ 。",
句号前空格

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
>  	"block.create.sequenced_gearshift.tooltip.summary": "一种可编程的组件，可以根据内部的指令改变旋转的_方向_，_速度_，以及_距离_。 此组件可以有效配合活塞和轴承等使用。最高可让其按_顺序_执行_5条指令_。条高速旋转时可能会变得不精确。",
此组件前有空格

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.rope_pulley.tooltip.summary": "移动绳索相连的结构. 使用_底盘_或者_粘液块_来移动多行方块。",
. -> 。

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.linear_chassis.tooltip.action1": "变为_粘性机壳底盘_. 所有工作范围内与其相连的方块会与其_一同移动_。",
. -> 。

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.radial_chassis.tooltip.behaviour2": "配置连接的方块的半径.按住_Ctrl_可以同时配置相连的其他底盘。",
. -> 。

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.radial_chassis.tooltip.action1": "变为_粘性旋转底盘_.所有工作范围内与其相连的方块会与其_一同移动_。",
. -> 。

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.mechanical_plough.tooltip.summary": "犁是一个非常有用的多功能方块， 它可以被 _动力活塞_ 和 _动力轴承_ 等带动。",
他可以 前 空格

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.belt_tunnel.tooltip.summary": "这是一种美观的方块，能够让_传送带_穿过墙壁时更美观， 但是传送带必须被黄铜机壳包装才能在上方放置此方块. 如果启动了_同步模式_，且旁边有_传送带隧道_时， 将会等待其他所有传送带隧道的物品_一起通过_. [Ctrl]。",
第 2 4 个逗号后 空格

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.belt_tunnel.tooltip.action1": "启动_同步模式_， 同步模式下，只有临近的_所有_同步模式的传送带隧道都有物品时才会_一齐通过_。",
逗号后空格

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.belt_observer.tooltip.summary": "检测_传送带_上经过侦测器的物品、实体. 使用_扳手_将可以修改它的模式. 非物品实体总会以观测模式经行侦测. 可进行物品标记。",
. -> 。

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"tool.create.sand_paper.tooltip.summary": "用来_打磨_物品的砂纸， 可以用机械臂来实现自动化。",
逗号后空格

2020-08-11 14:37 UTC, Imbarainbow commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.blockzapper.component.body": "放置器机体",
支持原来的 2 个字的，只修改 “寻回”，
原因：虽改变词性，但游戏内查看并不会造成误解且 GUI Friendly，不会有过长的显示

2020-08-11 14:54 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
>  	"advancement.create.overstressed.desc": "首次使能量网络超载.",
nb，这是我用正则做的，结果还是有漏网之鱼

2020-08-11 14:54 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.gui.stockpile_switch.stopBelow": "停止红石信号当容量小于",
这个是因为在gui上，没办法修改语序，这 后面就直接是要输入的数字了

2020-08-11 15:06 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.recipe.pressing": "金属压板",
可

2020-08-11 15:24 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.blockzapper.component.scope": "范围观察器",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

@LWHK 
这里给出原译，我的译法以及原文，同时给出部分资料以供参考，说一说你们的意见

<details>
<summary>原文</summary>
```

	"create.blockzapper.component.body": "Body",
	"create.blockzapper.component.amplifier": "Amplifier",
	"create.blockzapper.component.accelerator": "Accelerator",
	"create.blockzapper.component.retriever": "Retriever",
	"create.blockzapper.component.scope": "Scope",

···

</details>

<details>
<summary>原译</summary>
```

	"create.blockzapper.component.body": "机体",
	"create.blockzapper.component.amplifier": "增大",
	"create.blockzapper.component.accelerator": "加速",
	"create.blockzapper.component.retriever": "寻回",
	"create.blockzapper.component.scope": "范围",

···

</details>

<details>
<summary>我的译法</summary>
```

	"create.blockzapper.component.body": "放置器机体",
	"create.blockzapper.component.amplifier": "范围扩大器",
	"create.blockzapper.component.accelerator": "冷却加速器",
	"create.blockzapper.component.retriever": "物品回捡器",
	"create.blockzapper.component.scope": "范围观察器",

···

</details>

部分参考资料：
[中文对应wiki页面](https://github.com/Imbarainbow/Create/wiki/%E6%89%8B%E6%8C%81%E6%96%B9%E5%9D%97%E6%94%BE%E7%BD%AE%E5%99%A8)
[英文对应wiki链接](https://github.com/Creators-of-Create/Create/wiki/The-Handheld-Blockzapper)

2020-08-12 02:34 UTC, WuzgXY-GitHub commented
谁叫我？

2020-08-12 02:37 UTC, TUsama commented
> 谁叫我？

看上面

2020-08-12 05:59 UTC, WuzgXY-GitHub commented
没找到星鱼可以啊，不愧是裂文唬客

2020-09-06 08:09 UTC, merged

2020-09-07 13:54 UTC, MacrousHyucen reviewed
详细问题发到群里了