0.3翻译
LWHK/Create pull request #3
Opened 2020-11-28 09:55 UTC by TUsama

2020-12-21 02:25 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.generic.unit.millibuckets":"%1$smB",
```suggestion
	"create.generic.unit.millibuckets":"%1$s mB",
```

2020-12-21 02:25 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.action.discard":"丢弃",
```suggestion
	"create.action.discard":"放弃",
```

2020-12-21 02:25 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.recipe.mystery_conversion":"化合物变异",
```suggestion
	"create.recipe.mystery_conversion":"神秘转化",
```

2020-12-21 02:25 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"advancement.create.shadow_steel":"虚空归来的宝石",
```suggestion
	"advancement.create.shadow_steel":"虚空归来者",

```

2020-12-21 03:23 UTC, MacrousHyucen requested changes
目前1.15.2版本行数为1788 
1.16版本为1792
是否有出现漏译情况，或是部分内容不需要翻译？

2020-12-21 03:23 UTC, MacrousHyucen commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"advancement.create.dual_extendo_grip.desc": "双持伸展抓拿手，这简直不是人类的触及距离",
双持伸展抓拿手，你好长啊~

2020-12-21 03:23 UTC, MacrousHyucen commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"create.gui.attribute_filter.whitelist_conjunctive": "全匹配白名单 (所有)",
全部

2020-12-21 06:43 UTC, Snownee commented
unfinished目录里的不需要改动

2020-12-21 06:50 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.hint.upward_funnel":"只可以传送由 _动力臂_，鼓风机驱动的 _溜槽_ 或者被投掷的物品。试着做一些溜槽来垂直运输物品。",
为什么有的空格有的则没有？

2020-12-21 06:53 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.depot":"贮物台",
```suggestion
	"block.create.depot":"置物台",
```

2020-12-21 06:56 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.pink_sail":"粉色风帆",
```suggestion
	"block.create.pink_sail":"粉红色风帆",
```
粉色 -> 粉红色。下同

2020-12-21 07:00 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"fluid.create.flowing_potion":"药剂",
这个条目新版本里不存在。你应该先拉取

2020-12-22 03:33 UTC, MacrousHyucen approved these changes

2020-12-22 03:34 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.hint.upward_funnel":"只可以传送由 _动力臂_，鼓风机驱动的 _溜槽_ 或者被投掷的物品。试着做一些溜槽来垂直运输物品。",
这个是非常严重的历史遗留问题，我之前已经尽量在下划线的前或后加上空格了，但难免有疏漏，还麻烦一一指出。

2020-12-22 03:37 UTC, TUsama commented on src/generated/resources/assets/create/lang/unfinished/zh_cn.json
> +	"advancement.create.dual_extendo_grip.desc": "双持伸展抓拿手，这简直不是人类的触及距离",
我不太认可这种容易让人引起误解的翻译。。像之前的“目力工程师”都被我改掉了。

2020-12-22 03:43 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.hint.upward_funnel":"只可以传送由 _动力臂_，鼓风机驱动的 _溜槽_ 或者被投掷的物品。试着做一些溜槽来垂直运输物品。",
先解决版本问题再说吧

2020-12-22 03:45 UTC, TUsama commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"create.hint.upward_funnel":"只可以传送由 _动力臂_，鼓风机驱动的 _溜槽_ 或者被投掷的物品。试着做一些溜槽来垂直运输物品。",
我尽量。

2020-12-22 08:54 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"item.create.blaze_cake": "烈焰蛋糕",
```suggestion
		"item.create.blaze_cake": "熔岩蛋糕",
```

2020-12-22 08:56 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"death.attack.create.crush": "%1$s 被压扁了",
```suggestion
		"death.attack.create.crush": "%1$s被压扁了",
```

2020-12-22 09:08 UTC, Snownee requested changes

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"death.attack.create.fan_fire": "%1$s 试图接受热风的洗礼",
```suggestion
		"death.attack.create.fan_fire": "%1$s试图接受热风的洗礼",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"death.attack.create.cuckoo_clock_explosion": "%1$s 被布谷鸟钟炸得粉身碎骨",
```suggestion
		"death.attack.create.cuckoo_clock_explosion": "%1$s被布谷鸟钟炸得粉身碎骨",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"death.attack.create.mechanical_saw": "%1$s 被圆锯切成了两截",
```suggestion
		"death.attack.create.mechanical_saw": "%1$s被圆锯切成了两截",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"death.attack.create.mechanical_drill": "%1$s 被钻头钻的坏掉了",
```suggestion
		"death.attack.create.mechanical_drill": "%1$s被钻头钻的坏掉了",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"death.attack.create.fan_lava": "%1$s 在接受热风的洗礼中欲火焚身",
```suggestion
		"death.attack.create.fan_lava": "%1$s在接受热风的洗礼中欲火焚身",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"create.recipe.fan_blasting.fan": "在岩浆后放置鼓风机",
```suggestion
		"create.recipe.fan_blasting.fan": "在熔岩后放置鼓风机",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.encased_fan.tooltip.behaviour1": "可将鼓风机下方的 _热能_ （火，岩浆等）转化成 _动能_ ，需要将鼓风机向下摆放。",
```suggestion
	"block.create.encased_fan.tooltip.behaviour1": "可将鼓风机下方的 _热能_ （火、熔岩等）转化成 _动能_ ，需要将鼓风机向下摆放。",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.encased_fan.tooltip.condition3": "当气流通过火，水，岩浆时",
```suggestion
	"block.create.encased_fan.tooltip.condition3": "当气流通过火、水、熔岩时",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.encased_fan.tooltip.behaviour3": "在 _被吹出_ 的水，火，岩浆粒子中放置物品会获得相应产物( _建议配合jei查看_ )。",
```suggestion
	"block.create.encased_fan.tooltip.behaviour3": "在 _被吹出_ 的水、火、熔岩粒子中放置物品会获得相应产物( _建议配合jei查看_ )。",
```

2020-12-22 09:08 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.portable_storage_interface.tooltip.summary": "一种便携的 _物品接口_ ，能够将移动的结构中的物品进行交互移动。",
这个条目更新过。

2020-12-22 09:11 UTC, Snownee commented
https://github.com/Creators-of-Create/Create/commit/2744cabf142b58304f266c3792ddbacdc50b7e15#diff-e2530a35ed922e0b91fbd56a9bc1264cd940049fc5cb32d4caa2ce1d059438c3

2020-12-22 09:16 UTC, Snownee requested changes

2020-12-22 09:16 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +	"block.create.hand_crank.tooltip.summary": "一种简单的旋转能源，需要 _人工转动_。",
这个条目更新过。

2020-12-22 09:17 UTC, Snownee commented
记得把`src/generated/resources/assets/create/lang/unfinished/zh_cn.json`里的改动清掉

2020-12-22 11:40 UTC, MacrousHyucen commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"create.recipe.fan_blasting.fan": "在岩浆后放置鼓风机",
lava目前仍然译作岩浆 建议仍然保留岩浆的叫法

2020-12-22 13:05 UTC, Snownee commented on src/main/resources/assets/create/lang/zh_cn.json
> +		"create.recipe.fan_blasting.fan": "在岩浆后放置鼓风机",
@MacrousHyucen https://minecraft-zh.gamepedia.com/%E7%86%94%E5%B2%A9 吓得我赶紧又看了眼wiki

2020-12-25 13:22 UTC, MacrousHyucen approved these changes

2020-12-25 14:36 UTC, merged