done
LWHK/Create pull request #9
Opened 2021-01-03 02:58 UTC by TUsama

2021-01-03 14:40 UTC, TUsama commented
有几个没翻译的，在这里提一提意见吧（叹气）

2021-01-07 14:07 UTC, MacrousHyucen requested changes
好耶

2021-01-07 14:07 UTC, MacrousHyucen commented on src/main/resources/assets/create/lang/zh_cn.json
>  	"create.gui.schematicannon.shotsRemaining": "发射进度：%1$s",
here

2021-01-07 14:13 UTC, MacrousHyucen requested changes
上面是余量下面是储备（拍头

2021-01-07 14:56 UTC, MacrousHyucen approved these changes

2021-01-25 08:45 UTC, MacrousHyucen approved these changes

2021-01-28 14:03 UTC, MacrousHyucen approved these changes
好！

2021-01-30 08:21 UTC, Snownee approved these changes

2021-03-07 06:04 UTC, closed without merging